trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
jobs:
- job: Release
  steps:
  - checkout: self
  - script: exit 1
- job: PostRelease
  condition: always()
  dependsOn: Release
  variables:
    ReleaseStatus: $[dependencies.Release.result]  # Note: no spaces and use [] not $()
  steps:
  - checkout: self
  - script: echo "$(ReleaseStatus)"
