trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
jobs:
- job: Release
  steps:
  - checkout: self
  - script: exit 1
- job: PostRelease
  condition: always()
  dependsOn: Release
  steps:
  - checkout: self
  - script: |
      echo "Release Result: $(dependencies.Release.result)"
      echo "Release Status: $(dependencies.Release.status)"
    displayName: 'dump dependencies'
  - script: |
      echo "Job Status Variables:"
      echo "SYSTEM_JOBSTATUS: $(SYSTEM_JOBSTATUS)"
      echo "AGENT_JOBSTATUS: $(AGENT_JOBSTATUS)"
    displayName: 'dump job status'
