trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
jobs:
- job: Release
  steps:
  - checkout: self
  - script: exit 1
- job: PostRelease
  condition: always()
  dependsOn: Release
  steps:
  - checkout: self
  - script: echo "${{ convertToJson(variables) }}"
    displayName: 'dump variables'
  - script: echo "passed"
    displayName: passed
    condition: succeeded()
  - script: echo "passed"
    displayName: passed
    condition: succeeded()
